apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hash               
  template:
    metadata:
      labels:
        app: hash
    spec:
      containers:
      - name: hash-container
        image: anzeda/hash:v1
        ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: hash-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    app: hash